# Generated by Django 6.0.1 on 2026-01-23 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partvault', '0002_item_acquired_at_item_last_tested_at_item_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='acquired_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='last_tested_at',
        ),
        migrations.AddField(
            model_name='item',
            name='acquired_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='last_tested_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partvault.collection'),
        ),
    ]
