# Generated by Django 6.0.1 on 2026-01-23 21:11

import django.db.models.deletion
import partvault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partvault', '0004_documenttype_document_linktype_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=partvault.models.upload_path_photo)),
                ('is_thumbnail', models.BooleanField(default=False, help_text='Photo used as thumbnail')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partvault.item')),
            ],
        ),
    ]
