# Generated by OpenCode on 2026-01-25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("partvault", "0006_alter_collection_asset_tag_prefix_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="asset_tag_prefix",
            new_name="collection_code",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="asset_tag_prefix",
            new_name="user_code",
        ),
    ]
