# Generated by Django 6.0.1 on 2026-01-25 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partvault', '0007_rename_asset_tag_prefix_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AssetTagSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('assigned', 'Assigned'), ('void', 'Void')], default='reserved', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partvault.item')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
