# Generated by Django 6.0.1 on 2026-01-25 19:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partvault', '0008_item_asset_tag_assettagsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_profiles', to='partvault.collection'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_code',
            field=models.CharField(help_text='Required. 1 to 3 alphanumeric characters, code for this collection, for display only.', max_length=3, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_code',
            field=models.CharField(help_text='Required. 1 to 3 alphanumeric characters, unique to you, displayed to others.', max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
