# Generated by Django 6.0.1 on 2026-01-28 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partvault', '0009_profile_active_collection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partvault.collection')),
            ],
            options={
                'verbose_name_plural': 'locations',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partvault.location'),
        ),
    ]
