# Generated by Django 6.0.1 on 2026-01-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partvault', '0010_location_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
