# Generated by Django 6.0.1 on 2026-01-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partvault', '0011_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
