# Generated by Django 6.0.1 on 2026-01-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partvault', '0012_item_release_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name'], 'verbose_name_plural': 'statuses'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='status',
            name='color',
            field=models.CharField(choices=[('bg-primary', 'Primary'), ('bg-secondary', 'Secondary'), ('bg-success', 'Success'), ('bg-danger', 'Danger'), ('bg-warning', 'Warning'), ('bg-info', 'Info'), ('bg-light', 'Light'), ('bg-dark', 'Dark')], default='bg-info', max_length=20),
        ),
    ]
