# Generated by Django 6.0.1 on 2026-02-05 00:00

from django.conf import settings
from django.db import migrations, models


def copy_collection_owner_to_user(apps, schema_editor):
    for model_name in ("Category", "Manufacturer", "Status", "Tag"):
        model = apps.get_model("partvault", model_name)
        for instance in model.objects.select_related("collection__owner").filter(
            collection__isnull=False
        ):
            instance.user_id = instance.collection.owner_id
            instance.save(update_fields=["user"])


class Migration(migrations.Migration):
    dependencies = [
        (
            "partvault",
            "0013_alter_category_options_alter_manufacturer_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="status",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(copy_collection_owner_to_user, migrations.RunPython.noop),
        migrations.RemoveField(model_name="category", name="collection"),
        migrations.RemoveField(model_name="manufacturer", name="collection"),
        migrations.RemoveField(model_name="status", name="collection"),
        migrations.RemoveField(model_name="tag", name="collection"),
    ]
