# Generated by Django 6.0.1 on 2026-02-06 00:00

import django.db.models.deletion
from django.db import migrations, models


def copy_document_types_to_link_types(apps, schema_editor):
    Document = apps.get_model("partvault", "Document")
    DocumentType = apps.get_model("partvault", "DocumentType")
    LinkType = apps.get_model("partvault", "LinkType")

    link_type_ids = {}

    for document_type in DocumentType.objects.all():
        key = (document_type.user_id, document_type.name)
        link_type, _ = LinkType.objects.get_or_create(
            user_id=document_type.user_id,
            name=document_type.name,
        )
        link_type_ids[key] = link_type.id

    for document in Document.objects.select_related("document_type").filter(
        document_type__isnull=False
    ):
        document_type = document.document_type
        key = (document_type.user_id, document_type.name)
        link_type_id = link_type_ids.get(key)
        if link_type_id is None:
            link_type, _ = LinkType.objects.get_or_create(
                user_id=document_type.user_id,
                name=document_type.name,
            )
            link_type_id = link_type.id
            link_type_ids[key] = link_type_id
        document.shared_link_type_id = link_type_id
        document.save(update_fields=["shared_link_type"])


class Migration(migrations.Migration):
    dependencies = [
        ("partvault", "0016_user_owned_document_link_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="shared_link_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="partvault.linktype",
            ),
        ),
        migrations.RunPython(copy_document_types_to_link_types, migrations.RunPython.noop),
        migrations.RemoveField(model_name="document", name="document_type"),
        migrations.RenameField(
            model_name="document",
            old_name="shared_link_type",
            new_name="document_type",
        ),
        migrations.DeleteModel(name="DocumentType"),
    ]
