# Generated by Django 6.0.1 on 2026-02-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partvault', '0017_share_document_and_link_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
