# Generated by Django 6.0.1 on 2026-02-11 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partvault', '0018_item_manufacture_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-updated_at']},
        ),
    ]
